name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path: ./.github/actions/prepare-release
    permissions:
      contents: read

  build-gardenlogin:
    permissions:
      contents: read
    strategy:
      matrix:
        args:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
          - os: darwin
            arch: amd64
            runner: ubuntu-latest
          - os: darwin
            arch: arm64
            runner: ubuntu-24.04-arm
          - os: windows
            arch: amd64
            runner: ubuntu-latest
    runs-on: ${{ matrix.args.runner }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: build-gardenlogin
        shell: bash
        run: |
          set -euo pipefail

          mkdir /tmp/blobs.d

          LD_FLAGS="$(hack/get-build-ld-flags.sh)" \
          GOOS=${{ matrix.args.os }} \
          GOARCH=${{ matrix.args.arch }} \
          out_file="/tmp/blobs.d/gardenlogin-${{ matrix.args.os}}-${{ matrix.args.arch }}" \
            hack/build.sh
      - uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            name: gardenlogin
            relation: local
            type: executable
            extraIdentity:
              os: ${{ matrix.args.os }}
              architecture: ${{ matrix.args.arch }}
            access:
              type: localBlob
              localReference: >-
                gardenlogin-${{ matrix.args.os }}-${{ matrix.args.arch }}

  sast-lint:
    uses: gardener/cc-utils/.github/workflows/sastlint-ocm.yaml@master
    permissions:
      contents: read
    with:
      linter: gosec
      run: |
        set -eu
        TEST_COV=yes \
          .ci/verify
